/**
 * Phase 29 Plan 06 — per-session CSRF token helper.
 *
 * 29-CONTEXT.md decision: sameSite='lax' blocks the typical CSRF attack
 * class, but state-changing browser routes (POST /auth/logout, future
 * POST /me/tokens HTML, POST /me/tokens/:id/revoke) still get a
 * token-and-validate belt-and-braces layer.
 *
 * Generate-on-first-read: forms call this from the GET handler that
 * renders them, so the token lands in the session BEFORE the user POSTs.
 * Length = 256 bits hex (64 chars).
 *
 * Constant-time comparison via crypto.timingSafeEqual prevents timing
 * side-channels — even though the cookie is sealed and the token is
 * per-session, leaking comparison timing would still be a hygiene
 * regression.
 */
import { randomBytes, timingSafeEqual } from 'node:crypto';
import type { FastifyRequest } from 'fastify';

/** 64 lowercase hex chars = 256 bits. */
const TOKEN_HEX_LEN = 64;
const TOKEN_HEX_RE = /^[0-9a-f]{64}$/;

/**
 * Read the session's existing CSRF token if present and well-formed;
 * otherwise generate a new 256-bit token, store it in the session, and
 * return it. Idempotent for callers that invoke it from every GET that
 * embeds a form.
 *
 * Self-heals against tampering: a session value of the wrong length
 * (manual edit, migration drift) is treated as absent and rewritten.
 */
export function getOrCreateCsrfToken(request: FastifyRequest): string {
  const existing = request.session.get('csrf');
  if (typeof existing === 'string' && existing.length === TOKEN_HEX_LEN) {
    return existing;
  }
  const token = randomBytes(TOKEN_HEX_LEN / 2).toString('hex');
  request.session.set('csrf', token);
  return token;
}

/**
 * Constant-time verification of a supplied CSRF token against the
 * session's stored value. Returns true iff both:
 *   1. session.csrf is a 64-char hex string (i.e. was generated by
 *      getOrCreateCsrfToken), AND
 *   2. supplied is a 64-char hex string that matches byte-for-byte.
 *
 * Length / type prechecks run BEFORE timingSafeEqual so a malformed
 * supplied value never reaches the comparison; this is safe because the
 * existence of a token (length 64) is not a secret — knowing whether the
 * caller has a session at all is observable via the cookie itself.
 */
export function verifyCsrfToken(
  request: FastifyRequest,
  supplied: unknown,
): boolean {
  if (typeof supplied !== 'string' || supplied.length !== TOKEN_HEX_LEN) {
    return false;
  }
  if (!TOKEN_HEX_RE.test(supplied)) {
    return false;
  }
  const expected = request.session.get('csrf');
  if (typeof expected !== 'string' || expected.length !== TOKEN_HEX_LEN) {
    return false;
  }
  if (!TOKEN_HEX_RE.test(expected)) {
    return false;
  }
  // timingSafeEqual requires equal-length Buffers; the length-64 / hex-shape
  // prechecks above ensure both decode to identical 32-byte buffers.
  try {
    return timingSafeEqual(
      Buffer.from(expected, 'hex'),
      Buffer.from(supplied, 'hex'),
    );
  } catch {
    return false;
  }
}
