/**
 * Phase 29 Plan 03: thin wrapper around openid-client@6 functional API.
 *
 * Two reasons for the wrapper:
 *   1. Centralizes the "disabled vs configured" lifecycle. `initOidc`
 *      returns null when OIDC is intentionally off (so route handlers
 *      register 501 stubs); throws when OIDC is configured but broken
 *      (so boot exits 78 — Plan 8's responsibility).
 *   2. Gives tests and Plan 6 route handlers ONE place to mock instead of
 *      sprawling openid-client imports.
 *
 * Anti-pattern guard: NEVER call openid-client functions directly from
 * route handlers; always go through this module so library upgrades have
 * one diff surface.
 */
import * as client from 'openid-client';
import type { Config } from '../config/env.js';

export type OidcConfig = client.Configuration;

/**
 * Boot-time discovery.
 *   - Returns null when OIDC_ISSUER_URL is unset (caller registers 501 routes).
 *   - Returns a Configuration on discovery success.
 *   - Throws when OIDC_ISSUER_URL is set but discovery fails. The thrown
 *     Error's message includes the issuer URL so the boot wrapper (Plan 8)
 *     can log it before mapping to process.exit(78).
 *
 * No module-level state — multiple calls (e.g. tests) yield independent
 * Configurations. The env schema's all-or-nothing refine catches missing
 * client_id/secret at boot, but `initOidc` re-validates defensively because
 * direct test invocations can bypass the refine.
 */
export async function initOidc(env: Config): Promise<OidcConfig | null> {
  if (!env.OIDC_ISSUER_URL) return null;
  if (!env.OIDC_CLIENT_ID || !env.OIDC_CLIENT_SECRET) {
    throw new Error(
      'initOidc: OIDC_CLIENT_ID and OIDC_CLIENT_SECRET must be set when OIDC_ISSUER_URL is set',
    );
  }
  try {
    return await client.discovery(
      new URL(env.OIDC_ISSUER_URL),
      env.OIDC_CLIENT_ID,
      env.OIDC_CLIENT_SECRET,
    );
  } catch (err) {
    const cause = err instanceof Error ? err.message : String(err);
    throw new Error(
      `OIDC discovery failed for ${env.OIDC_ISSUER_URL}: ${cause}`,
      { cause: err },
    );
  }
}

export interface AuthorizationUrlParams {
  /**
   * Pre-computed PKCE code_challenge (S256). The caller is responsible for
   * generating and stashing the matching code_verifier in the session
   * cookie BEFORE the redirect is sent — Plan 6's responsibility.
   */
  pkceCodeChallenge: string;
  /** Opaque CSRF state value; the caller mirrors this into the session cookie. */
  state: string;
  /** Optional ID-token nonce; emitted as `nonce=` when present. */
  nonce?: string;
  /** Redirect URI registered with the IdP (must match callback handler). */
  redirectUri: string;
  /** Space-separated scopes string (e.g. "openid email profile"). */
  scopes: string;
}

/**
 * Build the authorization URL. Pure synchronous helper — the PKCE verifier
 * + state are generated by the caller (Plan 6) so the same values can be
 * stashed in the encrypted cookie BEFORE the redirect is sent.
 *
 * Always emits `code_challenge_method=S256`; openid-client v6 will reject
 * non-S256 challenges at the IdP and the Phase 29 fixture only advertises
 * S256 anyway.
 */
export function buildAuthorizationUrl(
  config: OidcConfig,
  params: AuthorizationUrlParams,
): URL {
  const oidcParams: Record<string, string> = {
    redirect_uri: params.redirectUri,
    scope: params.scopes,
    code_challenge: params.pkceCodeChallenge,
    code_challenge_method: 'S256',
    state: params.state,
  };
  if (params.nonce) oidcParams.nonce = params.nonce;
  return client.buildAuthorizationUrl(config, oidcParams);
}

export interface CallbackChecks {
  /**
   * PKCE code_verifier (NOT the challenge); the token endpoint hashes it
   * server-side and compares against the challenge sent with the
   * authorization request.
   */
  pkceVerifier: string;
  /** Must match the `state` query param on the callback URL byte-for-byte. */
  expectedState: string;
  /** Optional ID-token nonce check (when the authorize step requested one). */
  expectedNonce?: string;
}

/**
 * Exchange the authorization code for tokens. `currentUrl` must be the
 * full callback URL (the upstream library extracts `code` + `state` from
 * the query string). Throws on state mismatch, code-exchange failure,
 * signature failure, expired/issuer/aud mismatch — openid-client handles
 * all these internally per AUTH-03.
 */
export async function handleCallback(
  config: OidcConfig,
  currentUrl: URL,
  checks: CallbackChecks,
): Promise<client.TokenEndpointResponse & client.TokenEndpointResponseHelpers> {
  return client.authorizationCodeGrant(config, currentUrl, {
    pkceCodeVerifier: checks.pkceVerifier,
    expectedState: checks.expectedState,
    ...(checks.expectedNonce !== undefined
      ? { expectedNonce: checks.expectedNonce }
      : {}),
  });
}

export interface EndSessionUrlParams {
  /** ID token from the authorization-code grant; used as the logout hint. */
  idTokenHint: string;
  /** Where the IdP should redirect after RP-initiated logout completes. */
  postLogoutRedirectUri: string;
}

/**
 * Returns the RP-initiated logout URL when the IdP advertised
 * `end_session_endpoint` in discovery. Returns null otherwise so the caller
 * (Plan 6 /auth/logout) can fall back to a local redirect.
 *
 * openid-client throws synchronously when end_session_endpoint is absent;
 * we catch that here and convert to a null return so callers don't have to
 * mirror the try/catch.
 */
export function buildEndSessionUrl(
  config: OidcConfig,
  params: EndSessionUrlParams,
): URL | null {
  try {
    return client.buildEndSessionUrl(config, {
      id_token_hint: params.idTokenHint,
      post_logout_redirect_uri: params.postLogoutRedirectUri,
    });
  } catch {
    // openid-client throws when end_session_endpoint is absent. Treat as
    // "logout endpoint not advertised" — caller falls back.
    return null;
  }
}

/** PKCE + state/nonce helpers re-exported so callers don't import openid-client directly. */
export const randomPKCECodeVerifier = client.randomPKCECodeVerifier;
export const calculatePKCECodeChallenge = client.calculatePKCECodeChallenge;
export const randomState = client.randomState;
export const randomNonce = client.randomNonce;
