import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createHash, randomUUID } from 'node:crypto';
import { parse, stringify } from 'smol-toml';
import { resolveAssetPath } from '../assets/resolve.js';

const OWNER = 'wood-fired-tasks';
const MANIFEST = '.wood-fired-tasks/manifest.json';
export type SetupTarget = 'claude' | 'codex';
export interface CodexCopyResult {
  sourceDir: string;
  destDir: string;
  written: string[];
  files: string[];
}
interface Manifest {
  owner: typeof OWNER;
  schema: 1;
  files: Record<string, string>;
}
export function codexSkillsDir(home = os.homedir()): string {
  return path.join(home, '.agents', 'skills');
}
export function codexConfigPath(
  home = os.homedir(),
  codexHome = process.env['CODEX_HOME'],
): string {
  return path.join(codexHome || path.join(home, '.codex'), 'config.toml');
}
function hash(bytes: Buffer): string {
  return createHash('sha256').update(bytes).digest('hex');
}
function safeRelative(file: string): boolean {
  return (
    !file.includes('\\') &&
    !file.split('/').includes('..') &&
    /^(?:tasks-[a-z0-9-]+\/|\.wood-fired-tasks\/references\/)/.test(file)
  );
}
/** Refuse links, including dangling links, rather than writing through them. */
function checkPath(file: string, boundary: string): void {
  const parent = path.dirname(file);
  if (file !== boundary && parent !== file) checkPath(parent, boundary);
  try {
    if (fs.lstatSync(file).isSymbolicLink()) throw new Error(`Refusing to modify symlink: ${file}`);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
  }
}
function readManifest(destDir: string): Manifest | null {
  const file = path.join(destDir, MANIFEST);
  checkPath(file, path.dirname(destDir));
  if (!fs.existsSync(file)) return null;
  try {
    const data = JSON.parse(fs.readFileSync(file, 'utf8')) as Manifest;
    if (
      data.owner !== OWNER ||
      data.schema !== 1 ||
      !data.files ||
      typeof data.files !== 'object' ||
      Array.isArray(data.files) ||
      Object.entries(data.files).some(
        ([name, digest]) =>
          !safeRelative(name) || typeof digest !== 'string' || !/^[a-f0-9]{64}$/.test(digest),
      )
    )
      throw new Error('invalid');
    return data;
  } catch {
    throw new Error(
      `Invalid Wood Fired Tasks ownership manifest at ${file}; preserve a backup and resolve it before retrying setup.`,
    );
  }
}
export function hasCodexInstallation(home = os.homedir()): boolean {
  return readManifest(codexSkillsDir(home)) !== null;
}
function listFiles(dir: string, prefix = ''): string[] {
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .flatMap((entry) => {
      const name = prefix + entry.name;
      if (entry.isDirectory()) return listFiles(path.join(dir, entry.name), `${name}/`);
      if (!entry.isFile()) throw new Error(`Unexpected bundled asset: ${name}`);
      return [name];
    })
    .sort();
}
function writeAtomic(file: string, bytes: Buffer | string): void {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const temp = `${file}.tmp-${randomUUID()}`;
  try {
    fs.writeFileSync(temp, bytes, { mode: 0o600, flag: 'wx' });
    fs.renameSync(temp, file);
  } finally {
    if (fs.existsSync(temp)) fs.unlinkSync(temp);
  }
}
/** All conflicts are checked before copying. Only unchanged, owned files update. */
export function copyCodexSkills(
  destDir = codexSkillsDir(),
  sourceDir = resolveAssetPath('dist', 'skills', 'codex'),
  dryRun = false,
): CodexCopyResult {
  const files = listFiles(sourceDir);
  if (!files.some((file) => /^tasks-[a-z0-9-]+\/SKILL\.md$/.test(file)))
    throw new Error('Bundled Codex skills are missing; reinstall wood-fired-tasks.');
  const previous = readManifest(destDir);
  const next: Manifest = { owner: OWNER, schema: 1, files: {} };
  const conflicts = new Set<string>();
  const contents = new Map<string, Buffer>();
  for (const file of files) {
    if (!safeRelative(file)) throw new Error(`Invalid bundled Codex asset path: ${file}`);
    const dest = path.join(destDir, file);
    checkPath(dest, path.dirname(destDir));
    const bytes = fs.readFileSync(path.join(sourceDir, file));
    contents.set(file, bytes);
    next.files[file] = hash(bytes);
    // Never adopt an existing user-authored skill directory, even if its
    // current SKILL.md happens to match our generated bytes.
    const directory = file.split('/')[0]!;
    const ownedDirectory = Object.keys(previous?.files ?? {}).some((owned) =>
      owned.startsWith(`${directory}/`),
    );
    if (!ownedDirectory && fs.existsSync(path.join(destDir, directory))) conflicts.add(directory);
    if (fs.existsSync(dest)) {
      if (!fs.statSync(dest).isFile() || previous?.files[file] !== hash(fs.readFileSync(dest)))
        conflicts.add(file);
    }
  }
  for (const [file, digest] of Object.entries(previous?.files ?? {})) {
    checkPath(path.join(destDir, file), path.dirname(destDir));
    if (
      fs.existsSync(path.join(destDir, file)) &&
      (!fs.statSync(path.join(destDir, file)).isFile() ||
        hash(fs.readFileSync(path.join(destDir, file))) !== digest)
    )
      conflicts.add(file);
  }
  if (conflicts.size)
    throw new Error(
      `Preserved conflicting Codex skills: ${[...conflicts].join(', ')}. Back up and move the conflicting skill directories outside ${destDir}, then re-run setup --target codex --skills-only. No files were changed.`,
    );
  const written: string[] = [];
  if (dryRun) return { sourceDir, destDir, written, files };
  for (const [file, bytes] of contents) {
    const dest = path.join(destDir, file);
    if (!fs.existsSync(dest) || !bytes.equals(fs.readFileSync(dest))) {
      writeAtomic(dest, bytes);
      written.push(file);
    }
  }
  for (const file of Object.keys(previous?.files ?? {})) {
    if (!(file in next.files) && fs.existsSync(path.join(destDir, file)))
      fs.unlinkSync(path.join(destDir, file));
  }
  const serialized = `${JSON.stringify(next, null, 2)}\n`;
  const manifestPath = path.join(destDir, MANIFEST);
  if (!fs.existsSync(manifestPath) || fs.readFileSync(manifestPath, 'utf8') !== serialized)
    writeAtomic(manifestPath, serialized);
  return { sourceDir, destDir, written, files };
}

export interface CodexMcpOptions {
  home?: string;
  codexHome?: string;
  serverName: string;
  entry: { command: string; args: string[]; env: Record<string, string> };
}
/** Validate first; append only absent entries so existing settings/comments survive. */
export function planCodexMcp(options: CodexMcpOptions): {
  filePath: string;
  content: string;
  changed: boolean;
} {
  const filePath = codexConfigPath(options.home, options.codexHome);
  checkPath(filePath, path.dirname(filePath));
  const raw = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : '';
  let parsed: Record<string, unknown>;
  try {
    parsed = parse(raw);
  } catch {
    throw new Error(
      `Cannot parse ${filePath}; configuration was preserved. Repair the TOML and retry.`,
    );
  }
  const servers = parsed['mcp_servers'] as Record<string, unknown> | undefined;
  const other = options.serverName === OWNER ? `${OWNER}-remote` : OWNER;
  if (servers?.[other] !== undefined)
    throw new Error(
      `Existing Codex MCP server '${other}' was preserved. To switch modes, run codex mcp remove ${other}, then repeat setup. To install skills with your current connection, use setup --target codex --skills-only.`,
    );
  const existing = servers?.[options.serverName] as Record<string, unknown> | undefined;
  if (existing !== undefined) {
    const env = existing['env'] as Record<string, unknown> | undefined;
    const matches =
      existing['command'] === options.entry.command &&
      JSON.stringify(existing['args']) === JSON.stringify(options.entry.args) &&
      existing['enabled'] !== false &&
      Object.entries(options.entry.env).every(([key, value]) => env?.[key] === value);
    if (!matches)
      throw new Error(
        `Existing Codex MCP server '${options.serverName}' differs and was preserved. Use setup --target codex --skills-only to keep it, or back up ${filePath}, run codex mcp remove ${options.serverName}, and repeat setup to replace it.`,
      );
    return { filePath, content: raw, changed: false };
  }
  const addition = stringify({ mcp_servers: { [options.serverName]: options.entry } });
  const content = `${raw}${raw.endsWith('\n') || !raw ? '' : '\n'}\n${addition}`;
  try {
    parse(content);
  } catch {
    throw new Error(
      `Cannot safely append the MCP entry to ${filePath}; configuration was preserved. Use codex mcp add (see docs show setup), then setup --target codex --skills-only.`,
    );
  }
  return { filePath, content, changed: true };
}
export function writeCodexMcp(plan: ReturnType<typeof planCodexMcp>): void {
  if (plan.changed) writeAtomic(plan.filePath, plan.content);
}
