#!/usr/bin/env bash
set -euo pipefail

# Wood Fired Bugs - Deployment Setup
# Run as root or with sudo: sudo bash deploy/install.sh
#
# Prerequisites:
#   - Node.js installed at /usr/bin/node
#   - Project built (npm run build)
#   - sqlite3 CLI installed (sudo apt-get install sqlite3)
#
# What this script does:
#   1. Creates ${WFB_INSTALL_DIR} directory structure (default /opt/wood-fired-bugs)
#   2. Copies built application files
#   3. Installs production dependencies
#   4. Copies systemd unit file
#   5. Enables and starts the service
#
# Configurable env vars (see deploy/README.md):
#   WFB_INSTALL_DIR   Install path  (default: /opt/wood-fired-bugs)
#   WFB_SERVICE_USER  Service user  (default: wood-fired-bugs)
#
# After running, you MUST:
#   - Edit ${WFB_INSTALL_DIR}/.env to set real API_KEYS
#   - Run: sudo systemctl restart wood-fired-bugs

INSTALL_DIR="${WFB_INSTALL_DIR:-/opt/wood-fired-bugs}"
SOURCE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SERVICE_USER="${WFB_SERVICE_USER:-wood-fired-bugs}"

echo "=== Wood Fired Bugs Deployment ==="
echo "Install dir : $INSTALL_DIR"
echo "Service user: $SERVICE_USER"

# Create the service user as a locked-down system account if it doesn't exist
if ! id "$SERVICE_USER" &>/dev/null; then
  echo "Creating system user: $SERVICE_USER"
  useradd --system --no-create-home --shell /usr/sbin/nologin \
    --home-dir "$INSTALL_DIR" "$SERVICE_USER"
fi

# Create directory structure
mkdir -p "$INSTALL_DIR"/{data,backups,dist}

# Copy application files
cp -r "$SOURCE_DIR/dist/"* "$INSTALL_DIR/dist/"
cp "$SOURCE_DIR/package.json" "$INSTALL_DIR/"
cp "$SOURCE_DIR/package-lock.json" "$INSTALL_DIR/" 2>/dev/null || true

# Install production dependencies only
cd "$INSTALL_DIR"
npm install --omit=dev

# Copy env template if .env doesn't exist
if [ ! -f "$INSTALL_DIR/.env" ]; then
  cp "$SOURCE_DIR/deploy/wood-fired-bugs.env.example" "$INSTALL_DIR/.env"
  echo "WARNING: Created .env from template. Edit $INSTALL_DIR/.env to set API_KEYS before starting."
fi

# Set ownership
chown -R "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR"

# Install systemd unit
cp "$SOURCE_DIR/deploy/wood-fired-bugs.service" /etc/systemd/system/

# Write a systemd drop-in when overrides are in effect.
# The shipped unit hardcodes User=wood-fired-bugs and /opt/wood-fired-bugs so it
# stays valid as a static file; drop-ins layer on top without modifying the
# packaged unit (preserved across upgrades).
DEFAULT_INSTALL_DIR="/opt/wood-fired-bugs"
DEFAULT_SERVICE_USER="wood-fired-bugs"
if [ "$INSTALL_DIR" != "$DEFAULT_INSTALL_DIR" ] || [ "$SERVICE_USER" != "$DEFAULT_SERVICE_USER" ]; then
  DROPIN_DIR="/etc/systemd/system/wood-fired-bugs.service.d"
  mkdir -p "$DROPIN_DIR"
  cat > "$DROPIN_DIR/override.conf" <<EOF
# Auto-generated by deploy/install.sh -- do not edit by hand.
# Regenerate by re-running install.sh with WFB_INSTALL_DIR / WFB_SERVICE_USER set.
[Service]
User=$SERVICE_USER
Group=$SERVICE_USER
WorkingDirectory=$INSTALL_DIR
EnvironmentFile=$INSTALL_DIR/.env
ExecStart=
ExecStart=/usr/bin/node $INSTALL_DIR/dist/api/start.js
ReadWritePaths=
ReadWritePaths=$INSTALL_DIR/data $INSTALL_DIR/backups
EOF
  echo "Wrote systemd drop-in: $DROPIN_DIR/override.conf"
fi

systemctl daemon-reload
systemctl enable wood-fired-bugs

echo ""
echo "=== Deployment Complete ==="
echo "Next steps:"
echo "  1. Edit $INSTALL_DIR/.env (set API_KEYS)"
echo "  2. sudo systemctl start wood-fired-bugs"
echo "  3. sudo systemctl status wood-fired-bugs"
echo "  4. sudo journalctl -u wood-fired-bugs -f"
