#!/usr/bin/env bash
set -euo pipefail

# Wood Fired Bugs - Host Provisioning (install once, then run upgrade.sh)
# Run as root or with sudo: sudo bash deploy/install.sh
#
# This script provisions the HOST (service user, install directories, env
# template, systemd unit, drop-in override). It does NOT deploy the
# application artefacts -- that responsibility lives in deploy/upgrade.sh,
# which is run every time you ship a new build.
#
# The split exists so re-deploys (the common case) do not need to re-run
# host provisioning, and so the deploy step has its own backup + health
# probe + rollback recipe.
#
# Prerequisites:
#   - Node.js installed at /usr/bin/node
#   - sqlite3 CLI installed (sudo apt-get install sqlite3)
#
# What this script does:
#   1. Creates the ${WFB_SERVICE_USER} system account (if absent)
#   2. Creates ${WFB_INSTALL_DIR} directory structure
#   3. Seeds .env from deploy/wood-fired-bugs.env.example (if absent)
#   4. Installs the systemd unit at /etc/systemd/system/
#   5. Writes a drop-in override when WFB_INSTALL_DIR / WFB_SERVICE_USER
#      differ from the packaged defaults
#   6. Enables the service (does NOT start it -- upgrade.sh starts it)
#
# Configurable env vars (see deploy/README.md):
#   WFB_INSTALL_DIR   Install path  (default: /opt/wood-fired-bugs)
#   WFB_SERVICE_USER  Service user  (default: wood-fired-bugs)
#
# After running, the next step is ALWAYS:
#   sudo ./deploy/upgrade.sh
#
# upgrade.sh copies dist/ + package files, runs npm ci --omit=dev, applies
# migrations, starts the service, and probes /health. Re-run upgrade.sh on
# every subsequent deploy; you should not need to re-run install.sh unless
# you change install-dir / service-user policy.

INSTALL_DIR="${WFB_INSTALL_DIR:-/opt/wood-fired-bugs}"
SOURCE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SERVICE_USER="${WFB_SERVICE_USER:-wood-fired-bugs}"

echo "=== Wood Fired Bugs Deployment ==="
echo "Install dir : $INSTALL_DIR"
echo "Service user: $SERVICE_USER"

# Create the service user as a locked-down system account if it doesn't exist
if ! id "$SERVICE_USER" &>/dev/null; then
  echo "Creating system user: $SERVICE_USER"
  useradd --system --no-create-home --shell /usr/sbin/nologin \
    --home-dir "$INSTALL_DIR" "$SERVICE_USER"
fi

# Create directory structure. dist/ is created empty -- upgrade.sh fills it.
mkdir -p "$INSTALL_DIR"/{data,backups,dist}

# Copy env template if .env doesn't exist. upgrade.sh leaves .env untouched
# so this is the one place an operator picks up the template.
if [ ! -f "$INSTALL_DIR/.env" ]; then
  cp "$SOURCE_DIR/deploy/wood-fired-bugs.env.example" "$INSTALL_DIR/.env"
  echo "WARNING: Created .env from template. Edit $INSTALL_DIR/.env to set API_KEYS before running upgrade.sh."
fi

# Set ownership on the directories we just created. upgrade.sh re-chowns
# after it copies dist/ and runs npm ci.
chown -R "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR"

# Install systemd unit
cp "$SOURCE_DIR/deploy/wood-fired-bugs.service" /etc/systemd/system/

# Write a systemd drop-in when overrides are in effect.
# The shipped unit hardcodes User=wood-fired-bugs and /opt/wood-fired-bugs so it
# stays valid as a static file; drop-ins layer on top without modifying the
# packaged unit (preserved across upgrades).
DEFAULT_INSTALL_DIR="/opt/wood-fired-bugs"
DEFAULT_SERVICE_USER="wood-fired-bugs"
if [ "$INSTALL_DIR" != "$DEFAULT_INSTALL_DIR" ] || [ "$SERVICE_USER" != "$DEFAULT_SERVICE_USER" ]; then
  DROPIN_DIR="/etc/systemd/system/wood-fired-bugs.service.d"
  mkdir -p "$DROPIN_DIR"
  cat > "$DROPIN_DIR/override.conf" <<EOF
# Auto-generated by deploy/install.sh -- do not edit by hand.
# Regenerate by re-running install.sh with WFB_INSTALL_DIR / WFB_SERVICE_USER set.
[Service]
User=$SERVICE_USER
Group=$SERVICE_USER
WorkingDirectory=$INSTALL_DIR
EnvironmentFile=$INSTALL_DIR/.env
ExecStart=
ExecStart=/usr/bin/node $INSTALL_DIR/dist/api/start.js
ReadWritePaths=
ReadWritePaths=$INSTALL_DIR/data $INSTALL_DIR/backups
EOF
  echo "Wrote systemd drop-in: $DROPIN_DIR/override.conf"
fi

systemctl daemon-reload
systemctl enable wood-fired-bugs

echo ""
echo "=== Host Provisioning Complete ==="
echo "Next steps:"
echo "  1. Edit $INSTALL_DIR/.env (set API_KEYS)"
echo "  2. Build the app:           npm ci && npm run build"
echo "  3. Deploy the app:          sudo ./deploy/upgrade.sh"
echo "  4. Check service health:    sudo systemctl status wood-fired-bugs"
echo "  5. Follow logs:             sudo journalctl -u wood-fired-bugs -f"
echo ""
echo "On every subsequent release, only step 2+3 need to be repeated."
