import { Command } from 'commander';

const GLOBAL_FLAGS = ['--json', '--no-input', '--force', '--help', '--version'];

const STATUSES = ['open', 'in_progress', 'done', 'closed', 'blocked', 'backlogged'];
const PRIORITIES = ['low', 'medium', 'high', 'urgent'];

/**
 * Extract subcommand names + descriptions from a Commander program.
 *
 * This is the single source of truth for the completion command list — it reads
 * directly from the same `program` instance that `bin/tasks.ts` registers
 * commands on, so new commands automatically appear in shell completions
 * without a parallel hardcoded list to maintain.
 *
 * Filters out Commander's built-in `help` subcommand because it isn't a real
 * user-facing command.
 */
function getCommandSpecs(program: Command): Array<{ name: string; description: string }> {
  return program.commands
    .filter((cmd) => cmd.name() !== 'help')
    .map((cmd) => ({
      name: cmd.name(),
      description: cmd.description() || `${cmd.name()} command`,
    }));
}

function generateBashScript(program: Command): string {
  const specs = getCommandSpecs(program);
  const commandNames = specs.map((s) => s.name);
  return `# bash completion for tasks CLI
# Generated by: tasks completions bash
# Install: tasks completions bash >> ~/.bashrc
#   or:    tasks completions bash > /etc/bash_completion.d/tasks

_tasks_completions() {
  local cur prev commands global_flags statuses priorities
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"

  commands="${commandNames.join(' ')}"
  global_flags="${GLOBAL_FLAGS.join(' ')}"
  statuses="${STATUSES.join(' ')}"
  priorities="${PRIORITIES.join(' ')}"

  # Complete --status values
  if [[ "\${prev}" == "--status" ]]; then
    COMPREPLY=( $(compgen -W "\${statuses}" -- "\${cur}") )
    return 0
  fi

  # Complete --priority values
  if [[ "\${prev}" == "--priority" ]]; then
    COMPREPLY=( $(compgen -W "\${priorities}" -- "\${cur}") )
    return 0
  fi

  # Complete shell names for completions command
  if [[ "\${prev}" == "completions" ]]; then
    COMPREPLY=( $(compgen -W "bash zsh" -- "\${cur}") )
    return 0
  fi

  # Complete flags
  if [[ "\${cur}" == -* ]]; then
    COMPREPLY=( $(compgen -W "\${global_flags} --status --priority --assignee --tags --search --title --description --project" -- "\${cur}") )
    return 0
  fi

  # Complete commands (first argument after 'tasks')
  if [[ \${COMP_CWORD} -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "\${commands}" -- "\${cur}") )
    return 0
  fi
}

complete -F _tasks_completions tasks
`;
}

function generateZshScript(program: Command): string {
  const specs = getCommandSpecs(program);
  return `#compdef tasks
# zsh completion for tasks CLI
# Generated by: tasks completions zsh
# Install: tasks completions zsh > ~/.zsh/completions/_tasks
#   then add to .zshrc: fpath=(~/.zsh/completions $fpath)

_tasks() {
  local -a commands statuses priorities global_flags

  commands=(
    ${specs.map((s) => `'${s.name}:${s.name} command'`).join('\n    ')}
  )

  statuses=(${STATUSES.join(' ')})
  priorities=(${PRIORITIES.join(' ')})
  global_flags=(
    '--json[Output as JSON]'
    '--no-input[Disable interactive prompts]'
    '--force[Skip confirmation prompts]'
    '--help[Show help]'
    '--version[Show version]'
  )

  _arguments -C \\
    '1:command:->command' \\
    '*::arg:->args'

  case $state in
    command)
      _describe 'command' commands
      ;;
    args)
      case $words[1] in
        list)
          _arguments \\
            '--status[Filter by status]:status:(${STATUSES.join(' ')})' \\
            '--priority[Filter by priority]:priority:(${PRIORITIES.join(' ')})' \\
            '--assignee[Filter by assignee]:assignee:' \\
            '--tags[Filter by tags]:tags:' \\
            '--search[Search text]:search:' \\
            $global_flags
          ;;
        create|subtask-create)
          _arguments \\
            '--title[Task title]:title:' \\
            '--status[Task status]:status:(${STATUSES.join(' ')})' \\
            '--priority[Task priority]:priority:(${PRIORITIES.join(' ')})' \\
            '--project[Project ID]:project:' \\
            '--assignee[Assignee]:assignee:' \\
            '--description[Description]:description:' \\
            $global_flags
          ;;
        update)
          _arguments \\
            '--status[New status]:status:(${STATUSES.join(' ')})' \\
            '--priority[New priority]:priority:(${PRIORITIES.join(' ')})' \\
            '--title[New title]:title:' \\
            '--assignee[New assignee]:assignee:' \\
            $global_flags
          ;;
        completions)
          _arguments '1:shell:(bash zsh)'
          ;;
        *)
          _arguments $global_flags
          ;;
      esac
      ;;
  esac
}

_tasks
`;
}

/**
 * Build the `completions` Command, bound to the given root program so the
 * generated scripts reflect the exact set of registered subcommands.
 *
 * The factory shape (program -> Command) avoids a circular import: bin/tasks.ts
 * is the only place that constructs the root program, and it passes that
 * program in here when registering the completions subcommand.
 */
export function createCompletionsCommand(program: Command): Command {
  return new Command('completions')
    .description('Generate shell completion scripts')
    .argument('<shell>', 'Shell type: bash or zsh')
    .action((shell: string) => {
      switch (shell.toLowerCase()) {
        case 'bash':
          console.log(generateBashScript(program));
          break;
        case 'zsh':
          console.log(generateZshScript(program));
          break;
        default:
          console.error(`Unsupported shell: ${shell}. Use 'bash' or 'zsh'.`);
          process.exit(1);
      }
    });
}
